#!/usr/bin/env bash
# extract-db.sh — Extract Supabase PostgreSQL schema for C4 documentation
#
# Requires a running local Supabase instance (supabase start / pnpm supabase:start).
# Queries information_schema and pg_catalog — no DDL, token-efficient format.
#
# Usage (from repo root):
#   bash .claude/skills/c4-plantuml/scripts/extract-db.sh [--out=docs/c4/database.md]

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
OUT_FILE="${REPO_ROOT}/docs/c4/database.md"

for arg in "$@"; do
  case "$arg" in
    --out=*) OUT_FILE="${arg#--out=}" ;;
  esac
done

# ── Find Supabase DB container ────────────────────────────────────────────────

DB_CONTAINER="$(docker ps --format '{{.Names}}' 2>/dev/null \
  | grep -E 'supabase.*(db|postgres)|supabase_db' \
  | head -1 || true)"

if [[ -z "$DB_CONTAINER" ]]; then
  echo "[c4] ERROR: no running Supabase DB container found." >&2
  echo "[c4]   Start one with:  supabase start   or   pnpm supabase:start" >&2
  exit 1
fi

echo "[c4] using container: $DB_CONTAINER" >&2

PG="docker exec $DB_CONTAINER psql -U postgres -d postgres -t -A"

# ── Helpers ───────────────────────────────────────────────────────────────────

q() { $PG -c "$1" 2>/dev/null || true; }

# ── Tables ────────────────────────────────────────────────────────────────────

TABLES="$(q "
  SELECT table_name
  FROM information_schema.tables
  WHERE table_schema = 'public'
    AND table_type = 'BASE TABLE'
  ORDER BY table_name;")"

# ── Columns: table.column  type  [NOT NULL]  [DEFAULT] ────────────────────────

COLUMNS="$(q "
  SELECT
    table_name || '.' || column_name
      || '  ' || data_type
      || CASE WHEN is_nullable = 'NO' THEN '  NOT NULL' ELSE '' END
      || CASE WHEN column_default IS NOT NULL THEN '  DEFAULT' ELSE '' END
  FROM information_schema.columns
  WHERE table_schema = 'public'
  ORDER BY table_name, ordinal_position;")"

# ── Foreign keys: table.col → ref_table.ref_col ───────────────────────────────

FK="$(q "
  SELECT
    tc.table_name || '.' || kcu.column_name
      || '  →  '
      || ccu.table_name || '.' || ccu.column_name
  FROM information_schema.table_constraints tc
  JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name = kcu.constraint_name
   AND tc.table_schema    = kcu.table_schema
  JOIN information_schema.constraint_column_usage ccu
    ON ccu.constraint_name = tc.constraint_name
   AND ccu.table_schema    = tc.table_schema
  WHERE tc.constraint_type = 'FOREIGN KEY'
    AND tc.table_schema    = 'public'
  ORDER BY tc.table_name, kcu.column_name;")"

# ── Enums ─────────────────────────────────────────────────────────────────────

ENUMS="$(q "
  SELECT t.typname || ': ' || string_agg(e.enumlabel, ', ' ORDER BY e.enumsortorder)
  FROM pg_type t
  JOIN pg_enum e ON t.oid = e.enumtypid
  JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
  WHERE n.nspname = 'public'
  GROUP BY t.typname
  ORDER BY t.typname;")"

# ── Write ─────────────────────────────────────────────────────────────────────

mkdir -p "$(dirname "$OUT_FILE")"

{
  printf '<!-- Generated by c4-plantuml skill — do not edit manually -->\n\n'
  printf '# ClassroomIO — Database Schema\n\n'
  printf '> Extracted from local Supabase on %s\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  printf '## Tables\n\n```\n'
  [[ -n "$TABLES" ]] && echo "$TABLES" || echo "(none)"
  printf '```\n\n'

  printf '## Columns\n\n```\n'
  [[ -n "$COLUMNS" ]] && echo "$COLUMNS" || echo "(none)"
  printf '```\n\n'

  if [[ -n "$FK" ]]; then
    printf '## Foreign Keys\n\n```\n'
    echo "$FK"
    printf '```\n\n'
  fi

  if [[ -n "$ENUMS" ]]; then
    printf '## Enums\n\n```\n'
    echo "$ENUMS"
    printf '```\n\n'
  fi
} >"$OUT_FILE"

echo "[c4] wrote $OUT_FILE" >&2
