#!/usr/bin/env tsx
/**
 * Database Schema Extractor
 *
 * Connects to the local Supabase PostgreSQL container via docker exec,
 * queries information_schema for tables, columns, and foreign keys,
 * and writes a token-efficient markdown summary to docs/c4/database.md.
 *
 * Requires: supabase start (local Docker stack running)
 */

import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../../..");
const OUTPUT_FILE = path.join(REPO_ROOT, "docs/c4/database.md");

// ─── Docker helpers ───────────────────────────────────────────────────────────

function findSupabaseContainer(): string {
  try {
    const result = execSync(
      'docker ps --format "{{.Names}}" | grep -E "supabase.*(db|postgres)" | head -1',
      { encoding: "utf-8" }
    ).trim();
    if (!result) throw new Error("No container found");
    return result;
  } catch {
    // Fallback: try the default supabase local name
    const all = execSync('docker ps --format "{{.Names}}"', {
      encoding: "utf-8",
    });
    const match = all
      .split("\n")
      .find((n) => n.includes("supabase") && (n.includes("db") || n.includes("postgres")));
    if (!match) {
      throw new Error(
        "Could not find Supabase DB container. Is `supabase start` running?"
      );
    }
    return match.trim();
  }
}

function psql(container: string, sql: string): string {
  const escaped = sql.replace(/"/g, '\\"');
  return execSync(
    `docker exec ${container} psql -U postgres -d postgres -t -A -F'|' -c "${escaped}"`,
    { encoding: "utf-8" }
  );
}

// ─── Schema queries ───────────────────────────────────────────────────────────

interface Column {
  table: string;
  column: string;
  type: string;
  nullable: boolean;
  default: string | null;
}

interface ForeignKey {
  table: string;
  column: string;
  refTable: string;
  refColumn: string;
}

function fetchColumns(container: string): Column[] {
  const sql = `
    SELECT t.table_name, c.column_name, c.data_type, c.is_nullable, c.column_default
    FROM information_schema.tables t
    JOIN information_schema.columns c
      ON c.table_name = t.table_name AND c.table_schema = t.table_schema
    WHERE t.table_schema = 'public' AND t.table_type = 'BASE TABLE'
    ORDER BY t.table_name, c.ordinal_position;
  `;
  return psql(container, sql)
    .split("\n")
    .filter(Boolean)
    .map((line) => {
      const [table, column, type, nullable, def] = line.split("|");
      return {
        table,
        column,
        type: type?.replace("character varying", "varchar").replace("timestamp with time zone", "timestamptz"),
        nullable: nullable === "YES",
        default: def || null,
      };
    })
    .filter((c) => c.table && c.column);
}

function fetchForeignKeys(container: string): ForeignKey[] {
  const sql = `
    SELECT tc.table_name, kcu.column_name,
           ccu.table_name AS ref_table, ccu.column_name AS ref_column
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu
      ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage ccu
      ON ccu.constraint_name = tc.constraint_name AND ccu.table_schema = tc.table_schema
    WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema = 'public'
    ORDER BY tc.table_name, kcu.column_name;
  `;
  return psql(container, sql)
    .split("\n")
    .filter(Boolean)
    .map((line) => {
      const [table, column, refTable, refColumn] = line.split("|");
      return { table, column, refTable, refColumn };
    })
    .filter((fk) => fk.table && fk.column);
}

// ─── Markdown generation ──────────────────────────────────────────────────────

function generateMarkdown(columns: Column[], fks: ForeignKey[]): string {
  // Group columns by table
  const tables = new Map<string, Column[]>();
  for (const col of columns) {
    if (!tables.has(col.table)) tables.set(col.table, []);
    tables.get(col.table)!.push(col);
  }

  // Index FK lookups: "table.column" → "refTable.refColumn"
  const fkIndex = new Map<string, string>();
  for (const fk of fks) {
    fkIndex.set(`${fk.table}.${fk.column}`, `${fk.refTable}.${fk.refColumn}`);
  }

  const lines: string[] = [
    "# ClassroomIO Database Schema",
    "",
    `> Auto-generated by \`/c4-model\` skill. Token-efficient format for AI context.`,
    `> Generated: ${new Date().toISOString().split("T")[0]}`,
    "",
  ];

  for (const [tableName, cols] of Array.from(tables.entries()).sort()) {
    lines.push(`## ${tableName}`, "");
    lines.push("| column | type | refs |");
    lines.push("|--------|------|------|");

    for (const col of cols) {
      const fkTarget = fkIndex.get(`${tableName}.${col.column}`);
      const refs = fkTarget ? `→ ${fkTarget}` : "";
      const colType = col.nullable ? col.type : `${col.type} NOT NULL`;
      lines.push(`| ${col.column} | ${colType} | ${refs} |`);
    }
    lines.push("");
  }

  // Summary section
  lines.push("## Summary", "");
  lines.push(`- **Tables:** ${tables.size}`);
  lines.push(`- **Foreign keys:** ${fks.length}`);
  lines.push("");

  return lines.join("\n");
}

// ─── Entry point ──────────────────────────────────────────────────────────────

console.log("Finding Supabase container...");
const container = findSupabaseContainer();
console.log(`Using container: ${container}`);

console.log("Fetching columns...");
const columns = fetchColumns(container);
console.log(`  ${columns.length} columns across ${new Set(columns.map((c) => c.table)).size} tables`);

console.log("Fetching foreign keys...");
const fks = fetchForeignKeys(container);
console.log(`  ${fks.length} foreign keys`);

const markdown = generateMarkdown(columns, fks);
fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, markdown);
console.log(`\n✓ Schema written to ${OUTPUT_FILE}`);
