#!/usr/bin/env bash
# Extract database schema from a running local Supabase instance.
# Writes a token-efficient summary to docs/c4/database.md
#
# Prerequisites:
#   supabase start   (or have the containers already running)
#
# Usage:
#   bash .claude/skills/c4-model/db-schema.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
OUT_FILE="$REPO_ROOT/docs/c4/database.md"
PROJECT_ID="classroomio"
DB_CONTAINER="supabase_db_${PROJECT_ID}"
PSQL="docker exec -i $DB_CONTAINER psql -U postgres -d postgres -t -A"

# ── Check container is running ────────────────────────────────────────────────
if ! docker ps --filter "name=${DB_CONTAINER}" --format '{{.Names}}' | grep -q "$DB_CONTAINER"; then
  echo "Error: Container '$DB_CONTAINER' is not running."
  echo "Run 'supabase start' first."
  exit 1
fi

echo "Extracting schema from $DB_CONTAINER..."

mkdir -p "$REPO_ROOT/docs/c4"

# ── Helpers ───────────────────────────────────────────────────────────────────
# Runs a SQL query and returns tab-separated rows
run_sql() { $PSQL -c "$1"; }

# ── Tables + columns ─────────────────────────────────────────────────────────
TABLES_SQL="
SELECT t.table_name
FROM information_schema.tables t
WHERE t.table_schema = 'public'
  AND t.table_type = 'BASE TABLE'
ORDER BY t.table_name;
"

COLUMNS_SQL="
SELECT
  c.table_name,
  c.column_name,
  c.data_type,
  CASE WHEN c.is_nullable = 'NO' THEN 'NOT NULL' ELSE '' END AS nullable,
  COALESCE(c.column_default, '') AS col_default
FROM information_schema.columns c
WHERE c.table_schema = 'public'
ORDER BY c.table_name, c.ordinal_position;
"

# ── Foreign keys ──────────────────────────────────────────────────────────────
FK_SQL="
SELECT
  tc.table_name,
  kcu.column_name,
  ccu.table_name  AS foreign_table,
  ccu.column_name AS foreign_column
FROM information_schema.table_constraints AS tc
JOIN information_schema.key_column_usage AS kcu
  ON tc.constraint_name = kcu.constraint_name
  AND tc.table_schema   = kcu.table_schema
JOIN information_schema.constraint_column_usage AS ccu
  ON ccu.constraint_name = tc.constraint_name
  AND ccu.table_schema   = tc.table_schema
WHERE tc.constraint_type = 'FOREIGN KEY'
  AND tc.table_schema = 'public'
ORDER BY tc.table_name, kcu.column_name;
"

# ── Primary keys ──────────────────────────────────────────────────────────────
PK_SQL="
SELECT
  tc.table_name,
  kcu.column_name
FROM information_schema.table_constraints AS tc
JOIN information_schema.key_column_usage  AS kcu
  ON tc.constraint_name = kcu.constraint_name
  AND tc.table_schema   = kcu.table_schema
WHERE tc.constraint_type = 'PRIMARY KEY'
  AND tc.table_schema = 'public'
ORDER BY tc.table_name;
"

# ── Enums ─────────────────────────────────────────────────────────────────────
ENUM_SQL="
SELECT t.typname, e.enumlabel
FROM pg_type t
JOIN pg_enum e ON t.oid = e.enumtypid
JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
WHERE n.nspname = 'public'
ORDER BY t.typname, e.enumsortorder;
"

# ── Fetch all data ────────────────────────────────────────────────────────────
echo "  Fetching tables..."
TABLES=$(run_sql "$TABLES_SQL")

echo "  Fetching columns..."
COLUMNS=$(run_sql "$COLUMNS_SQL")

echo "  Fetching primary keys..."
PKS=$(run_sql "$PK_SQL")

echo "  Fetching foreign keys..."
FKS=$(run_sql "$FK_SQL")

echo "  Fetching enums..."
ENUMS=$(run_sql "$ENUM_SQL")

# ── Build lookup maps in awk and render markdown ──────────────────────────────
{
  echo "# ClassroomIO Database Schema"
  echo ""
  echo "> Auto-generated by \`db-schema.sh\`. Run \`supabase start\` then re-run to refresh."
  echo ""
  echo "## Tables"
  echo ""

  # For each table, print columns with PK/FK annotations
  while IFS= read -r table; do
    [[ -z "$table" ]] && continue
    echo "### \`$table\`"
    echo ""
    echo "| column | type | constraints |"
    echo "|--------|------|-------------|"

    while IFS=$'\t' read -r tbl col dtype nullable default_val; do
      [[ "$tbl" != "$table" ]] && continue

      constraints=""

      # Check PK
      if echo "$PKS" | awk -F'\t' -v t="$table" -v c="$col" '$1==t && $2==c {found=1} END {exit !found}'; then
        constraints="PK"
      fi

      # Check FK
      fk_ref=$(echo "$FKS" | awk -F'\t' -v t="$table" -v c="$col" '$1==t && $2==c {print "→" $3 "." $4}')
      if [[ -n "$fk_ref" ]]; then
        constraints="${constraints:+$constraints, }FK $fk_ref"
      fi

      # NOT NULL (skip for PK — implied)
      if [[ "$nullable" == "NOT NULL" && "$constraints" != *"PK"* ]]; then
        constraints="${constraints:+$constraints, }NOT NULL"
      fi

      # Default (only if non-trivial)
      if [[ -n "$default_val" && "$default_val" != *"nextval"* && "$default_val" != *"gen_random_uuid"* ]]; then
        constraints="${constraints:+$constraints, }DEFAULT $default_val"
      fi

      echo "| \`$col\` | \`$dtype\` | $constraints |"
    done <<< "$COLUMNS"

    echo ""
  done <<< "$TABLES"

  # ── Enums ──────────────────────────────────────────────────────────────────
  echo "## Enums"
  echo ""

  current_enum=""
  while IFS=$'\t' read -r typname label; do
    [[ -z "$typname" ]] && continue
    if [[ "$typname" != "$current_enum" ]]; then
      [[ -n "$current_enum" ]] && echo ""
      echo "**\`$typname\`**: \`$label\`"
      current_enum="$typname"
    else
      echo -n ", \`$label\`"
    fi
  done <<< "$ENUMS"

  echo ""
  echo ""
  echo "## Foreign Key Map"
  echo ""
  echo "| from | column | → | table.column |"
  echo "|------|--------|---|--------------|"

  while IFS=$'\t' read -r tbl col ftbl fcol; do
    [[ -z "$tbl" ]] && continue
    echo "| \`$tbl\` | \`$col\` | → | \`$ftbl\`.\`$fcol\` |"
  done <<< "$FKS"

} > "$OUT_FILE"

echo ""
echo "✓ Written: docs/c4/database.md"
echo "  Tables: $(echo "$TABLES" | grep -c '[a-z]')"
echo "  Foreign keys: $(echo "$FKS" | grep -c '[a-z]')"
