#!/usr/bin/env bash
# Extract a token-efficient summary of the local Supabase Postgres schema.
# Requires `supabase start` to be running. Output goes to stdout; redirect to
# docs/c4/database.md.
#
# Format per table:
#   ## schema.table  (rough row count if cheaply available)
#   col  type  [PK|FK→other.col|NULL|NOT NULL|DEFAULT ...]
#
# Designed for AI consumption — keep it compact. No full DDL, no indexes,
# no permissions. FKs are preserved so the relational graph is readable.
set -euo pipefail

CONTAINER="${SUPABASE_DB_CONTAINER:-supabase_db_classroomio}"

if ! docker ps --format '{{.Names}}' | grep -q "^${CONTAINER}$"; then
  # Try to auto-detect any running supabase_db_* container.
  CONTAINER="$(docker ps --format '{{.Names}}' | grep -E '^supabase_db_' | head -n1 || true)"
fi

if [ -z "${CONTAINER:-}" ] || ! docker ps --format '{{.Names}}' | grep -q "^${CONTAINER}$"; then
  echo "ERROR: No running supabase_db_* container. Run 'supabase start' first." >&2
  exit 1
fi

run_sql() {
  docker exec -i "$CONTAINER" psql -U postgres -d postgres -At -F $'\t' -c "$1"
}

cat <<'EOF'
## Database schema (local Supabase snapshot)

Generated by `.claude/skills/c4-model/extract-db.sh`. Token-efficient summary of the `public` schema — column type plus key markers, no full DDL. Foreign keys preserve the relational graph; everything else (indexes, triggers, RLS policies) is intentionally elided. Regenerate with the c4-model skill.

Legend: `PK` primary key, `FK→t.c` references `t.c`, `NN` not null, `D=…` default expression, `U` unique.

EOF

# Pull table list (public schema only, ordered).
TABLES=$(run_sql "
  SELECT table_name FROM information_schema.tables
  WHERE table_schema='public' AND table_type='BASE TABLE'
  ORDER BY table_name;
")

if [ -z "$TABLES" ]; then
  echo "_No tables in public schema._"
  exit 0
fi

# Columns + nullability + default.
COLUMNS_SQL="
  SELECT table_name, column_name, data_type, udt_name, is_nullable, column_default, ordinal_position
  FROM information_schema.columns
  WHERE table_schema='public'
  ORDER BY table_name, ordinal_position;
"

# Primary keys.
PK_SQL="
  SELECT kcu.table_name, kcu.column_name
  FROM information_schema.table_constraints tc
  JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name=kcu.constraint_name AND tc.table_schema=kcu.table_schema
  WHERE tc.constraint_type='PRIMARY KEY' AND tc.table_schema='public';
"

# Unique single-column constraints.
UQ_SQL="
  SELECT kcu.table_name, kcu.column_name
  FROM information_schema.table_constraints tc
  JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name=kcu.constraint_name AND tc.table_schema=kcu.table_schema
  WHERE tc.constraint_type='UNIQUE' AND tc.table_schema='public';
"

# Foreign keys.
FK_SQL="
  SELECT
    kcu.table_name      AS src_table,
    kcu.column_name     AS src_col,
    ccu.table_name      AS tgt_table,
    ccu.column_name     AS tgt_col
  FROM information_schema.table_constraints tc
  JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name=kcu.constraint_name AND tc.table_schema=kcu.table_schema
  JOIN information_schema.constraint_column_usage ccu
    ON tc.constraint_name=ccu.constraint_name AND tc.table_schema=ccu.table_schema
  WHERE tc.constraint_type='FOREIGN KEY' AND tc.table_schema='public';
"

# Approximate row counts (cheap; from pg_class).
ROWS_SQL="
  SELECT c.relname, c.reltuples::bigint
  FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE n.nspname='public' AND c.relkind='r';
"

TMP=$(mktemp -d)
trap "rm -rf $TMP" EXIT

run_sql "$COLUMNS_SQL" > "$TMP/cols.tsv"
run_sql "$PK_SQL"      > "$TMP/pk.tsv"
run_sql "$UQ_SQL"      > "$TMP/uq.tsv"
run_sql "$FK_SQL"      > "$TMP/fk.tsv"
run_sql "$ROWS_SQL"    > "$TMP/rows.tsv"

awk -F'\t' -v cols="$TMP/cols.tsv" -v pk="$TMP/pk.tsv" -v uq="$TMP/uq.tsv" -v fk="$TMP/fk.tsv" -v rows="$TMP/rows.tsv" '
BEGIN {
  while ((getline line < pk) > 0) { split(line, a, "\t"); is_pk[a[1] "\x01" a[2]] = 1 }
  while ((getline line < uq) > 0) { split(line, a, "\t"); is_uq[a[1] "\x01" a[2]] = 1 }
  while ((getline line < fk) > 0) { split(line, a, "\t"); fk_to[a[1] "\x01" a[2]] = a[3] "." a[4] }
  while ((getline line < rows) > 0) { split(line, a, "\t"); rowct[a[1]] = a[2] }
  while ((getline line < cols) > 0) {
    split(line, a, "\t")
    table = a[1]; col = a[2]; dt = a[3]; udt = a[4]; nn = (a[5]=="NO"); def = a[6]
    type = dt
    if (dt == "USER-DEFINED" || dt == "ARRAY") type = udt
    flags = ""
    key = table "\x01" col
    if (is_pk[key]) flags = flags " PK"
    if (key in fk_to) flags = flags " FK→" fk_to[key]
    if (is_uq[key]) flags = flags " U"
    if (nn) flags = flags " NN"
    if (def != "" && length(def) < 40) flags = flags " D=" def
    sub(/^ /, "", flags)
    if (table != cur) {
      if (cur != "") print ""
      r = rowct[table]
      if (r == "" || r == "-1") rs = ""
      else rs = " (~" r " rows)"
      print "## " table rs
      cur = table
    }
    if (flags == "") printf "- %s  %s\n", col, type
    else printf "- %s  %s  [%s]\n", col, type, flags
  }
}
' /dev/null
