#!/usr/bin/env bash
#
# extract-database.sh — write docs/c4/database.md from the running local
# Supabase Postgres container.
#
# Requires `pnpx supabase start` to be running first. Auto-locates the DB
# container by name pattern `supabase_db_*` (Supabase's default).
#
# Output: a token-efficient table-by-table schema:
#
#   ## courses
#   - id: uuid NOT NULL [PK]
#   - org_id: uuid NOT NULL -> organization.id
#   - title: text NOT NULL
#
# Foreign key references are preserved. Defaults and indexes are dropped
# because they are not useful for AI context. Edit the SQL below if you
# want them back.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../../.." && pwd)"
OUT="${OUT:-$REPO_ROOT/docs/c4/database.md}"
SCHEMA="${SCHEMA:-public}"

CONTAINER="$(docker ps --filter 'name=supabase_db_' --format '{{.Names}}' | head -n 1 || true)"
if [ -z "$CONTAINER" ]; then
  echo "Error: no running 'supabase_db_*' container found." >&2
  echo "Start Supabase first:  pnpx supabase start" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"

PSQL="docker exec -i $CONTAINER psql -U postgres -d postgres -At"

# ---- table list (header) ----
TABLE_LIST=$($PSQL -c "
SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind = 'r' AND n.nspname = '${SCHEMA}';
")

# ---- per-table schema ----
TABLES_MD=$($PSQL <<SQL
WITH cols AS (
  SELECT
    c.relname AS t,
    a.attname AS col,
    format_type(a.atttypid, a.atttypmod) AS typ,
    NOT a.attnotnull AS nullable,
    a.attnum AS pos
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  JOIN pg_attribute a ON a.attrelid = c.oid
  WHERE c.relkind = 'r'
    AND n.nspname = '${SCHEMA}'
    AND a.attnum > 0
    AND NOT a.attisdropped
),
pks AS (
  SELECT c.relname AS t, a.attname AS col
  FROM pg_index i
  JOIN pg_class c ON c.oid = i.indrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = ANY(i.indkey)
  WHERE i.indisprimary AND n.nspname = '${SCHEMA}'
),
fks AS (
  SELECT
    c.relname  AS t,
    a.attname  AS col,
    CASE WHEN nf.nspname <> '${SCHEMA}' THEN nf.nspname || '.' ELSE '' END
      || cf.relname AS rt,
    af.attname AS rc
  FROM pg_constraint con
  JOIN pg_class c       ON c.oid = con.conrelid
  JOIN pg_namespace n   ON n.oid = c.relnamespace
  JOIN pg_class cf      ON cf.oid = con.confrelid
  JOIN pg_namespace nf  ON nf.oid = cf.relnamespace
  JOIN LATERAL unnest(con.conkey)  WITH ORDINALITY AS k(attnum, ord)  ON TRUE
  JOIN LATERAL unnest(con.confkey) WITH ORDINALITY AS rk(attnum, ord) ON rk.ord = k.ord
  JOIN pg_attribute a   ON a.attrelid  = con.conrelid  AND a.attnum  = k.attnum
  JOIN pg_attribute af  ON af.attrelid = con.confrelid AND af.attnum = rk.attnum
  WHERE con.contype = 'f' AND n.nspname = '${SCHEMA}'
),
lines AS (
  SELECT
    cols.t,
    cols.pos,
    '- ' || cols.col || ': ' || cols.typ
      || CASE WHEN NOT cols.nullable THEN ' NOT NULL' ELSE '' END
      || CASE WHEN pks.col  IS NOT NULL THEN ' [PK]' ELSE '' END
      || CASE WHEN fks.col  IS NOT NULL THEN ' -> ' || fks.rt || '.' || fks.rc ELSE '' END
    AS line
  FROM cols
  LEFT JOIN pks ON pks.t = cols.t AND pks.col = cols.col
  LEFT JOIN fks ON fks.t = cols.t AND fks.col = cols.col
),
tabs AS (
  SELECT t, string_agg(line, E'\n' ORDER BY pos) AS body
  FROM lines
  GROUP BY t
)
SELECT '## ' || t || E'\n' || body || E'\n'
FROM tabs
ORDER BY t;
SQL
)

# ---- enums (handy for AI context, small payload) ----
ENUMS_MD=$($PSQL <<SQL
WITH e AS (
  SELECT t.typname AS name, string_agg(quote_literal(l.enumlabel), ', ' ORDER BY l.enumsortorder) AS vals
  FROM pg_type t
  JOIN pg_enum l ON l.enumtypid = t.oid
  JOIN pg_namespace n ON n.oid = t.typnamespace
  WHERE n.nspname = '${SCHEMA}'
  GROUP BY t.typname
)
SELECT '- ' || name || ': ' || vals FROM e ORDER BY name;
SQL
)

GENERATED_AT="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

{
  echo "# ClassroomIO database schema"
  echo
  echo "> Generated by \`.claude/skills/c4-model/extract-database.sh\` at ${GENERATED_AT}."
  echo "> Source: local Supabase Postgres container \`${CONTAINER}\`. Schema: \`${SCHEMA}\`."
  echo "> Foreign keys shown as \`-> table.column\`. Defaults and indexes are omitted."
  echo
  echo "## Tables"
  echo
  echo "${TABLE_LIST}"
  echo
  if [ -n "${ENUMS_MD// /}" ]; then
    echo "## Enums"
    echo
    echo "${ENUMS_MD}"
    echo
  fi
  echo "${TABLES_MD}"
} > "$OUT"

echo "Wrote $OUT"
